version: '3.1'

services:
    web:
        image: 127.0.0.1/flask-message-board
        build: .
        ports:
            - 5000:5000

    db:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ChangeM3!

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080